# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'kggMobil' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for kggMobil



  pod 'react-native-mixpanel', :path => '../node_modules/react-native-mixpanel'

end

